
# Define the name of the Go binary
BINARY_NAME=main.go

# Default target to build the binary

all: build

main:
  go run ${BINARY_NAME}

# Build the Go binary
build:
	go build -o $(BINARY_NAME)

# Run tests
test:
	go test ./...

# Clean up build artifacts
clean:
	rm -f $(BINARY_NAME)

# Run the Go application
run: build
	./$(BINARY_NAME)

# Format Go code
fmt:
	go fmt ./...

# Lint Go code (requires `golint` installed)
lint:
	golint ./...

# Show Go version
version:
	go version

